/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

public class App {
    public static void main(String[] args) {

        Telefone tel = new Telefone(123, "1A2B", "disco", 1.5, new Dimensao(5,2,1));

        Telefone semF = new SemFio(456, "2N6F", "A03", 0.3, new Dimensao(4,2,1), 5, 2, 300);

        // SemFio c = (SemFio) semF(456, "243", )

        System.out.println(tel.imprimirDados());

        System.out.println(semF.imprimirDados());





    }
}
