/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.produtos.Celular;
import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

public class App {
    public static void main(String[] args) {

        Telefone[] t = new Telefone[4];

        t[0] = new Telefone(123,"1F2T","A14", 2.4, new Dimensao(4,3,1));

        t[1] = new Celular(123,"1F2T","A14", 2.4, new Dimensao(4,3,1),20,2, 30, "Android");

        t[2] = new Celular(123,"1F2T","A14", 2.4, new Dimensao(4,3,1),20,2, 30, "Android");

        t[3] = new SemFio(123,"1F2T","A14", 2.4, new Dimensao(4,3,1), 30, 40, 60);

        for (Telefone tel : t) {
            System.out.println(tel.imprimirDados());

            if (tel instanceof Celular) {
                System.out.println(((Celular) tel).getSistemaOperacinal());
            }
        }






        /*
        c.setSistemaOperacinal("ios");

        ((Celular)t).setSistemaOperacinal("windows");

        */




        /*
        Telefone tel = new Telefone(123, "1A2B", "disco", 1.5, new Dimensao(5,2,1));

        Telefone semF = new SemFio(456, "2N6F", "A03", 0.3, new Dimensao(4,2,1), 5, 2, 300);

        // SemFio c = (SemFio) semF(456, "243", )

        System.out.println(tel.imprimirDados());

        System.out.println(semF.imprimirDados());

        */





    }
}
