/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);

        int[] moedas = new int[6];
        int opcao = 0;
        int somaAc = 0;

        do {
            System.out.println("Digite o valor da moeda: ");
            opcao = teclado.nextInt();

            switch (opcao) {

                case 1:
                    moedas[0]++;
                    somaAc += 1;
                    break;
                case 5:
                    moedas[1]++;
                    somaAc += 5;
                    break;
                case 10:
                    moedas[2]++;
                    somaAc += 10;
                    break;
                case 25:
                    moedas[3]++;
                    somaAc += 25;
                    break;
                case 50:
                    moedas[4]++;
                    somaAc += 50;
                    break;
                case 100:
                    moedas[5]++;
                    somaAc += 100;
                    break;
                default:
                    System.out.println("Valor Incorreto. Tente novamente ou digite 0 para finalizar.");
            }

        } while (opcao != 0);

        System.out.println("---------------------------");
        System.out.println("    Histograma - Moedas    ");
        System.out.println("---------------------------");

        System.out.print("1   | ");
        for (int i = 0; i < moedas[0]; i++) {
            System.out.print("*");
        }
        System.out.println();
        System.out.print("5   | ");
        for (int i = 0; i < moedas[1]; i++) {
            System.out.print("*");
        }
        System.out.println();
        System.out.print("10  | ");
        for (int i = 0; i < moedas[2]; i++) {
            System.out.print("*");
        }
        System.out.println();
        System.out.print("25  | ");
        for (int i = 0; i < moedas[3]; i++) {
            System.out.print("*");
        }
        System.out.println();
        System.out.print("50  | ");
        for (int i = 0; i < moedas[4]; i++) {
            System.out.print("*");
        }
        System.out.println();
        System.out.print("100 | ");
        for (int i = 0; i < moedas[5]; i++) {
            System.out.print("*");
        }

        System.out.println();
        System.out.println("---------------------------");

        double reais = (double) somaAc / 100;

        System.out.println("Quantidade de centavos: " + somaAc);
        System.out.printf("Valor Total: R$ %.2f%n", reais);

        teclado.close();
    }
}