/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in);

        while (teclado.hasNextLine()) {

            String linha = teclado.nextLine();

            System.out.println(linha.toUpperCase());

        }

    }

}
