/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.InputMismatchException;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner ler = new Scanner(System.in);

        /*
        int a, b;

        try {
            System.out.println("Entre com o número: ");
            a = ler.nextInt();
            System.out.println("Entre com o número: ");
            b = ler.nextInt();

            double res = (double) a / b;

            System.out.println(a + " dividido por " + b + " = " + res);
        } catch (Exception e) {
            System.out.println("Só é permitido números inteiros");
            ler.nextLine();
        }
        System.out.println("Fim do programa");

        */

    }

    public int lerTeclado(){
        Scanner teclado = new Scanner(System.in);
        do{
            try{
                System.out.print("Entre com um número: ");
                int num = teclado.nextInt();
                return num; // se o número for lido corretamente, então retorne
            }catch(Exception e){
                System.err.println("Erro: " + e.toString());
            }finally{
                System.out.print("Sempre será executada");
            }
            System.out.print("Se o return for executado, então essa linha nunca será alcançada");
        }while(true);
    }

}
