/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        Aldeao ald = new Aldeao(25, 1, 0.8);

        System.out.println(ald.atacar());
        System.out.println(ald.mover());

        Arqueiro arq = new Arqueiro(35, 2, 1);

        System.out.println(arq.atacar());
        System.out.println(arq.mover());

        Cavaleiro cav = new Cavaleiro(50,3,2);

        System.out.println(cav.atacar());
        System.out.println(cav.mover());

    }
}
