/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {

        Carro garagem = new Carro("fusca", "branco", new Motor(52, 1500));

        ArrayList<Motor> estante = new ArrayList<>();

        estante.add(garagem.getMotor());

        for (Motor e : estante) {
            System.out.println(e);
        }

        // troca de motor
        garagem.setMotor(new Motor(110, 2000));

        garagem = new Carro("uno", "branco", new Motor(40, 1000));

    }
}
