/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.*;

public class App {

    public static void main(String[] args) {

        ArrayList<String> nomes = new ArrayList<>();

        nomes.add("Ana");
        nomes.add("Bob");
        nomes.add("Juca");

        nomes.removeIf(e->e.equals("Ana"));

        ArrayList<Integer> numeros = new ArrayList<>();

        numeros.add(20);
        numeros.add(10);
        numeros.add(5);

        numeros.removeIf(e->e == 10);

        Collections.sort(numeros);

        numeros.forEach(System.out::println);

        Collections.shuffle(numeros);

        numeros.forEach(System.out::println);

        // for i
        for (int i = 0; i < numeros.size(); i++) {
            System.out.println(numeros.get(i));
        }

        // for each
        for (Integer elemento : numeros) {
            System.out.println(elemento);
        }

        // lambda
        numeros.forEach(elemento -> System.out.println(elemento));

        // method reference
        numeros.forEach(System.out::println);

        HashSet<String> conjunto = new HashSet<>();

        conjunto.add("Ana");
        conjunto.add("Ana");

        Queue<String> fila = new LinkedList<>();

        fila.add("Ana");
        fila.add("Juca");

        String n = fila.poll(); // retorna null se fila vazia // poll() existe apenas em Queue

    }

}
