/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        Caixa<Pessoa> c = new Caixa<>();

        Pessoa p = new Pessoa("Juca");

        c.setConteudo(p);

        Pessoa nova = c.getConteudo();

    }

}
