/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {


        /*
        Disciplina poo = new Disciplina("POO", new DiasDaSemana[]{ DiasDaSemana.TER, DiasDaSemana.SEX});

        System.out.println(poo.toString());

        DiasDaSemana d = DiasDaSemana.DOM;

        System.out.println(d.getCodigo());
        */

        // Sigla: POO
        // Dias:
        // - terça-feira
        // - sexta-feira

        for (Numeros n : Numeros.values()) {
            System.out.println(n);
        }



    }
}
