/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        ArrayList<Tarefa> tarefa = new ArrayList<>();




    }

}

/*
fazer sistema de gestao de tarefas

criar tarefas atividades do dia a dia

cada tarefa tem prazo de entrega, guardar data de conclusao

categorias: ex tarefas de poo

a cada tarefa associar pessoas  a essa tarefa

fazer diagrama uml das classes

 */


