/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFIo;
import ads.poo.produtos.Telefone;


public class App {

    public static void main(String[] args) {

        Telefone t = new Telefone(123, "123abc", "Galaxy",0.5, new Dimensao(6,12,1));

        SemFIo sf = new SemFIo(321,"123dfg", "Iphone", 0.5, new Dimensao(1,2,3), 1.5,2, 5);

        System.out.println(t.imprimirDados());

        System.out.println(sf.imprimirDados());

    }

}
