/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.HashMap;
import java.util.Scanner;
import java.time.LocalDate;

public class App {

    Scanner teclado;

    private HashMap<String, Aluno> bancoDeDados;

    public App() {

        this.bancoDeDados = new HashMap<>();
        this.teclado = new Scanner(System.in);
    }

    private int menu() {
        int opcao = 0;
        System.out.println("..::SIGAA 2 ::..");
        System.out.println("1 - Cadastrar");
        System.out.println("2 - Editar");
        System.out.println("3 - Excluir");
        System.out.println("4 - Listar dados de um aluno");
        System.out.println("5 - Listar todos os alunos");
        System.out.println("6 - Sair");

        // TODO ler a opcao

        return opcao;
    }

    private boolean cadastrar() {

        String matricula = "123";
        Aluno a = new Aluno("Bob", matricula, "ADS", "1234", "bob@example.com", LocalDate.of(2000,10,2));

        if (!this.bancoDeDados.containsKey(matricula)) {
            this.bancoDeDados.put(matricula, a);
            return true;
        }
        return false;

    }

    private boolean editar() {
        return false;
    }

    private void excluir() {

        String matricula = "123";

        if (this.bancoDeDados.remove(matricula) == null) {
            System.out.println("Não encontrada");
        } else {
            System.out.println("Removida com sucesso");
        }

    }

    private boolean listarDadosUmAluno() {

        System.out.println("Digite a matrícula: ");
        String mat = teclado.nextLine();

        if (mat == this.getMatricula()) {

        }


        return false;
    }

    private void listarTodosAlunos() {
        System.out.println(this.bancoDeDados);
    }

    private boolean sair() {
        return false;
    }



    public static void main(String[] args) {

        App app = new App();
        int opcao;

        do {
            opcao = app.menu();

            switch (opcao) {
                case 1 -> System.out.println("Cadastrando");
                case 2 -> app.editar();
                case 3 -> app.excluir();
                case 4 -> app.listarDadosUmAluno();
                case 5 -> app.listarTodosAlunos();
                case 6 -> app.sair();
                default -> System.out.println("Opção ínvalida");
            }
        } while (opcao != 6);





    }
}
