/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

public class App {

    Scanner teclado;

    private HashMap<String, Aluno> bancoDeDados;

    public App() {

        this.bancoDeDados = new HashMap<>();
        this.teclado = new Scanner(System.in);
    }

    private int menu() {
        int opcao = 0;
        System.out.println("..:: SIGAA ::..");
        System.out.println("1 - Cadastrar");
        System.out.println("2 - Editar");
        System.out.println("3 - Excluir");
        System.out.println("4 - Listar dados de um aluno");
        System.out.println("5 - Listar todos os alunos");
        System.out.println("6 - Sair");
        opcao = teclado.nextInt();
        teclado.nextLine();
        return opcao;
    }

    private boolean cadastrar() {

        System.out.println("Digite o nome: ");
        String nome = teclado.nextLine();

        System.out.println("Digite a matrícula: ");
        String matricula = teclado.nextLine();

        System.out.println("Digite o nome do curso: ");
        String curso = teclado.nextLine();

        System.out.println("Digite o número de telefone: ");
        String telefone = teclado.nextLine();

        System.out.println("Digite o endereço de email: ");
        String email = teclado.nextLine();

        System.out.println("Digite a data de nascimento: ");
        String dataString = teclado.nextLine();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(dataString, formato);

        Aluno a = new Aluno(nome, matricula, curso, telefone, email, data);

        if (!this.bancoDeDados.containsKey(matricula)) {
            this.bancoDeDados.put(matricula, a);
            return true;
        }
        return false;
    }

    private boolean editar() {

        System.out.println("Digite a matrícula: ");
        String matricula = teclado.nextLine();

        if (this.bancoDeDados.containsKey(matricula)) {
            
            System.out.println("Escolha uma opção para editar: ");
            System.out.println("1 - Nome");
            System.out.println("2 - Matrícula");
            System.out.println("3 - Curso");
            System.out.println("4 - Telefone");
            System.out.println("5 - Email");
            System.out.println("6 - Data de Nascimento");
            System.out.println("7 - Sair");

            int opcao = teclado.nextInt();
            teclado.nextLine();

            switch (opcao) {
                case 1 -> {
                    System.out.println("Digite o novo nome: ");
                    String novoNome = teclado.nextLine();
                }
                
                case 2 -> {
                    System.out.println("Digite o novo número de matrícula: ");
                    String novaMatricula = teclado.nextLine();

                    if (this.bancoDeDados.containsKey(novaMatricula)) {

                    } else {
                        System.out.println("Número de matrícula digitado não está disponível");
                    }
                }
                
                case 3 -> {
                    System.out.println("Atualize o nome do curso: ");
                    String cursoAtualizado = teclado.nextLine();
                }

                case 4 -> {
                    System.out.println("Digite o novo número de telefone: ");
                    String novoTelefone = teclado.nextLine();
                }

                case 5 -> {
                    System.out.println("Digite o novo endereço de email: ");
                    String novoEmail = teclado.nextLine();
                }

                case 6 -> {
                    System.out.println("Digite a nova data de nascimento: ");
                    String novaDataNascimento = teclado.nextLine();
                }

                case 7 -> {
                    return false;
                }

                default -> {
                    System.out.println("Opção inválida");
                }
            }

            return true;

        } else {
            System.out.println("Matrícula não encontrada");
            return false;
        }
    }

    private void excluir() {

        System.out.println("Digite a matrícula do aluno: ");
        String matricula = teclado.nextLine();

        if (this.bancoDeDados.remove(matricula) == null) {
            System.out.println("Matrícula não encontrada");
        } else {
            this.bancoDeDados.remove(matricula);
            System.out.println("Matrícula excluída com sucesso");
        }

    }

    private void listarDadosUmAluno() {

        System.out.println("Digite a matrícula: ");
        String matricula = teclado.nextLine();

        if (this.bancoDeDados.containsKey(matricula)) {
            System.out.println(this.bancoDeDados.get(matricula).toString());
        } else {
            System.out.println("Matrícula não encontrada");
        }

    }

    private void listarTodosAlunos() {
        System.out.println(this.bancoDeDados);
    }

    private boolean sair() {
        return false;
    }


    public static void main(String[] args) {

        App app = new App();
        int opcao;

        do {
            opcao = app.menu();

            switch (opcao) {
                case 1 -> System.out.println("Cadastrando");
                case 2 -> app.editar();
                case 3 -> app.excluir();
                case 4 -> app.listarDadosUmAluno();
                case 5 -> app.listarTodosAlunos();
                case 6 -> app.sair();
                default -> System.out.println("Opção ínvalida");
            }
        } while (opcao != 6);

    }
}