/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Telefone t = new Telefone("Pessoal", "48999999999");

        System.out.println(t);

        Email e = new Email("Pessoal", "meu.email@dominio.com.br");

        System.out.println(e);







        /*

        Classe Contato:

            Imprimir:

                Nome: Juca S...
                Data Nasc.: 20/...
                Telefones:
                    Pessoal: (48) 999...
                    Comercial: (48) 333...
                Emails:
                    Pessoal: juca@ifsc...

         */
    }

}
