/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Carro fusca = new Carro();

        fusca.definirModelo("Fusca");
        fusca.definirVelocidade(10);
        fusca.definirCor("azul");

        System.out.println(fusca.obterModelo() + " " + fusca.obterCor() + " está a " + fusca.obterVelocidade() + "Km/h.");

        Carro gol = new Carro();

        gol.definirModelo("Gol");
        gol.definirVelocidade(30);
        gol.definirCor("verde");

        System.out.println(gol.obterModelo() + " " + gol.obterCor() + " está a " + gol.obterVelocidade() + "Km/h");
        
    }
}
