/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        /*

        Carro fusca = new Carro();

        fusca.definirModelo("Fusca");
        fusca.definirVelocidade(10);
        fusca.definirCor("azul");

        System.out.println(fusca.obterModelo() + " " + fusca.obterCor() + " está a " + fusca.obterVelocidade() + "Km/h.");

        Carro gol = new Carro();

        gol.definirModelo("Gol");
        gol.definirVelocidade(30);
        gol.definirCor("verde");

        System.out.println(gol.obterModelo() + " " + gol.obterCor() + " está a " + gol.obterVelocidade() + "Km/h.");

        */

        /*

        Caneta c = new Caneta();
        Caneta d = new Caneta();

        c.definirCor("azul");
        c.definirNivelTinta(10);
        d.definirCor("verde");
        d.definirNivelTinta(100);

        System.out.println(c.desenhar(-15));
        System.out.println(d.desenhar(40));

        System.out.println(c.obterNivelTinta());
        System.out.println(d.obterNivelTinta());

        */

        /*

        Contador c = new Contador();

        System.out.println(c.obterValorAtual());
        c.definirValorContador(50);
        c.incrementarContador();
        System.out.println(c.obterValorAtual());

        */

        Buzz b = new Buzz();

        System.out.println(b.isAsasAbertas());
        System.out.println(b.isCapaceteAberto());

        System.out.println(b.abrirFecharAsas());
        System.out.println(b.abrirFecharCapacete());

        System.out.println(b.isAsasAbertas());
        System.out.println(b.isCapaceteAberto());

        System.out.println(b.abrirFecharAsas());
        System.out.println(b.abrirFecharCapacete());

        System.out.println(b.dispararLaser());
        System.out.println(b.golpearComBracoArticulado());

        System.out.println(b.falarFrase());
        System.out.println(b.falarFrase());
        
    }
}
