/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;

import java.awt.*;

public class App {

    private Draw draw;

    public App() {
        this.draw = new Draw();
        this.draw.setCanvasSize(600,300);
        this.draw.setXscale(0, 600);
        this.draw.setYscale(0,300);
    }

    public static void main(String[] args) {

        App app = new App();

        Circulo c = new Circulo(300,150,20, Color.green);

        // c.desenhar(app.draw);

        Grade g = new Grade(15,15,20,4,4, Color.blue);

        g.desenhar(app.draw);



        /*

        App app = new App();

        app.draw.circle(300, 150, 10);

        Color verde = new Color(50,160,65);

        app.draw.setPenColor(verde);

        app.draw.filledRoundRectangle(300,150,50,50,50,50);

        */


    }






}
