/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        Aldeao aldeao = new Aldeao();

        Arqueiro arqueiro = new Arqueiro();

        Cavaleiro cavaleiro = new Cavaleiro();

        System.out.println(aldeao.mover());
        System.out.println(aldeao.atacar());

        System.out.println(arqueiro.mover());
        System.out.println(arqueiro.atacar());

        System.out.println(cavaleiro.mover());
        System.out.println(cavaleiro.atacar());


    }

}
