/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.figura.Ponto;

public class App {

    public static void main(String[] args) {

        Aldeao aldeao = new Aldeao();

        Arqueiro arqueiro = new Arqueiro();

        Cavaleiro cavaleiro = new Cavaleiro();

        System.out.println(aldeao.mover());
        System.out.println(aldeao.atacar());

        System.out.println(arqueiro.mover());
        System.out.println(arqueiro.atacar());

        System.out.println(cavaleiro.mover());
        System.out.println(cavaleiro.atacar());

        System.out.println();

        // Objetos do pacote "figura"

        Ponto p = new Ponto("Preto", 2, 6);

        System.out.println(p.desenhar());


    }

}
